name: Inspection

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.9]
        os: ['ubuntu-latest', 'windows-latest']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install codespell flake8 -r requirements.txt
    - name: Test
      run: |
        echo index.%EXT% > tmp_wordlist.txt
        echo home.html >> tmp_wordlist.txt
        echo testphp.vulnweb.com > tmp_targets.txt
        echo "GET / HTTP/1.1" > tmp_raw.txt
        echo "Host: google.com" >> tmp_raw.txt
        echo "User-Agent: dirsearch" >> tmp_raw.txt
        echo "Accept: */*" >> tmp_raw.txt
        python3 dirsearch.py -w tmp_wordlist.txt -u https://example.com -o tmp_report.json --format json --force-recursive -R 3 --full-url -q -O
        python3 dirsearch.py -w tmp_wordlist.txt -l tmp_targets.txt --subdirs /,admin/ --exclude-extensions conf -q -L -f -i 200 --user-agent a --log tmp_log.log
        python3 dirsearch.py -w tmp_wordlist.txt -u https://localhost --ip 93.184.216.34 --max-rate 2 -H K:V --random-agent --overwrite-extensions --no-color
        python3 dirsearch.py -w tmp_wordlist.txt --raw tmp_raw.txt --prefixes . --suffixes ~ --skip-on-status 404 -m POST -d test=1 --crawl --min-response-size 9
        echo https://self-signed.badssl.com | python3 dirsearch.py -w tmp_wordlist.txt --stdin --max-time 9 --auth u:p --auth-type basic --scheme http

    - name: Unit Test
      run: python3 testing.py

    - name: Lint
      run: |
        flake8 .
    - name: Codespell
      run: codespell
